apiVersion: v1
kind: Service
metadata:
  name: queue-api
spec:
  selector:
    app: queue
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: queue-redis
spec:
  selector:
    app: queue-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
