{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.serviceName }}
    name: {{ .Values.serviceName }}
spec:
  ports:
    - name: {{ .Values.servicePort }}-tcp
      port: {{ .Values.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.targetPort }}
  selector:
    app.kubernetes.io/component: {{ .Values.serviceName }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}